F/kafka connect
aureliusenterprise/Aurelius-Atlas-helm-chart pull request #8
Opened 2024-04-29 06:53 UTC by lorandvatamany

2024-04-29 06:53 UTC, lorandvatamany commented
Work in progress, still need to update the readme

2024-05-08 04:12 UTC, thijs-franck approved these changes

2024-05-10 09:41 UTC, matjgora requested changes
Clean up the commented stuff please, then we merge

2024-05-10 09:41 UTC, matjgora commented on charts/flink/templates/jobmanager-session-deployment-non-ha.yaml
> -        lifecycle:
delete instead of comment

2024-05-10 09:41 UTC, matjgora commented on charts/flink/templates/taskmanager-session-deployment.yaml
> +        # lifecycle:
delete instead of comment

2024-05-10 09:41 UTC, matjgora commented on charts/kafka-ui/values.yaml
> +  # kafka:
delete comments

2024-05-10 09:41 UTC, matjgora commented on charts/kafka-ui/values.yaml
> +    # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_SCOPE: openid
delete comments

2024-05-10 09:41 UTC, matjgora commented on charts/keycloak/templates/statefulset.yaml
> +             #  value:  /{{ .Release.Namespace }}/auth
delete comment

2024-05-10 09:41 UTC, matjgora commented on charts/keycloak/templates/statefulset.yaml
> +            #   mountPath: /init/create_user.sh
delete comments

2024-05-10 09:41 UTC, matjgora commented on charts/keycloak/values.yaml
> +tag: "16.1.0.1"
is this the latest tag?

2024-05-10 09:41 UTC, matjgora commented on charts/python-rest/values.yaml
> +#external_hostname: "aureliusdev.westeurope.cloudapp.azure.com"
delete comment

2024-05-10 09:41 UTC, matjgora commented on charts/reverse-proxy/conf.d/atlas2.yaml
> +#<Location /atlas2/>
delete comments

2024-05-10 09:41 UTC, matjgora commented on charts/reverse-proxy/conf.d/flink.yaml
> -#OIDCProviderMetadataURL https://{{ .Values.global.external_hostname }}/{{ .Release.Namespace }}/auth/realms/m4i/.well-known/openid-configuration
delete comments

2024-05-10 09:41 UTC, matjgora commented on charts/reverse-proxy/conf.d/kafka-connect.yaml
> +#OIDCProviderMetadataURL https://{{ .Values.global.external_hostname }}/{{ .Release.Namespace }}/auth/realms/m4i/.well-known/openid-configuration
delete comments

2024-05-10 09:41 UTC, matjgora commented on charts/reverse-proxy/values.yaml
> +#external_hostname: "aureliusdev.westeurope.cloudapp.azure.com"
delete comment

2024-05-10 11:26 UTC, matjgora approved these changes

2024-05-13 15:36 UTC, merged